spring:
  cache:
    type: redis
  redis:
    ssl: true
    host: danceschool.redis.cache.windows.net
    port: 6380
    password: Rg98IbQPtmRFOlzvyHG6f1Z1T6smKQTYwU8O7iQNh4o=
    abortConnect: False
    allowAdmin: True
